name: Export and Upload Docker Image

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  export_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull Docker image
        run: |
          docker pull ubuntu:22.04
          docker tag ubuntu:22.04 exported-image:latest

      - name: Save Docker image to tar file
        run: |
          docker save -o exported-image.tar exported-image:latest

      - name: Upload Docker image to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./exported-image.tar
          asset_name: ubuntu-22.04-image.tar
          asset_content_type: application/x-tar